apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: /cilium-setters
  name: cilium-setters
  annotations:
    config.kubernetes.io/local-config: "true"
    internal.kpt.dev/function-config: apply-setters
    description.kpt.dev: Local setters for HelmChartConfig substitution within cilium-config
    internal.kpt.dev/upstream-identifier: '|ConfigMap|default|cilium-setters'
data:
  cluster-name: sample
  cluster-id: 7
