apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: mesh
  annotations:
    config.kubernetes.io/local-config: "true"  
resources:
  - tailscale
  - headscale
  - headplane


