apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: /rke2-core
  name: core.yaml
  annotations:
    description.kpt.dev: Core RKE2 settings
    config.kubernetes.io/local-config: "true"
data:
  write-kubeconfig-mode: "0640"
  bind-address: "0.0.0.0"
  cni:
    - cilium
  ingress-controller: traefik
