apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: /rke2-disable
  name: disable.yaml
  annotations:
    description.kpt.dev: Disable list fragment
    config.kubernetes.io/local-config: "true"
data:
  disable:
    - rke2-snapshot-controller
    - rke2-snapshot-controller-crd
    - rke2-snapshot-validation-webhook
    - rke2-ingress-nginx
