apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: /rke2-etcd-metrics
  name: etcd-metrics.yaml
  annotations:
    description.kpt.dev: Etcd metrics fragment
    config.kubernetes.io/local-config: "true"
data:
  etcd-expose-metrics: true
