apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: /rke2-etcd
  name: etcd.yaml
  annotations:
    description.kpt.dev: Etcd settings fragment
    config.kubernetes.io/local-config: "true"
data:
  etcd-expose-metrics: false
  node-name: ${cluster-name}-${node-name} # kpt-set: ${cluster-name}-${node-name}
  with-node-id: false
