apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: /rke2-token
  name: token.yaml
  annotations:
    description.kpt.dev: RKE2 token fragment
    config.kubernetes.io/local-config: "true"
data:
  token: ${cluster-token} # kpt-set: ${cluster-token}
