---
apiVersion: v1
data:
  enable-bundles-resolver: "true"
  enable-cluster-resolver: "true"
  enable-git-resolver: "true"
  enable-hub-resolver: "true"
kind: ConfigMap
metadata:
  annotations:
    kpt.dev/package-layer: system
    kpt.dev/package-name: tekton-pipelines
  labels:
    app.kubernetes.io/component: resolvers
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-pipelines
  name: resolvers-feature-flags
  namespace: tekton-pipelines
