---
apiVersion: v1
data:
  cap: 60s
  duration: 10s
  factor: "2.0"
  jitter: "0.0"
  steps: "5"
kind: ConfigMap
metadata:
  annotations:
    kpt.dev/package-layer: system
    kpt.dev/package-name: tekton-pipelines
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-pipelines
  name: config-wait-exponential-backoff
  namespace: tekton-pipelines
