---
apiVersion: v1
data:
  default-kind: task
  default-service-account: default
kind: ConfigMap
metadata:
  annotations:
    kpt.dev/package-layer: system
    kpt.dev/package-name: tekton-pipelines
  labels:
    app.kubernetes.io/component: resolvers
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-pipelines
  name: bundleresolver-config
  namespace: tekton-pipelines
