---
apiVersion: v1
data:
  config-init.sh: "#!/usr/bin/env -S bash -exuo pipefail\nmkdir -p /config\ncp /config-source/config.yaml /config/config.yaml\nmkdir -p /var/lib/headscale\nif [ ! -f /var/lib/headscale/extra_records.json ]; then \n  echo \"[]\" > /var/lib/headscale/extra_records.json; \nfi\ncp /extra-records-source/extra_records.json /var/lib/headscale/extra_records.json"
kind: ConfigMap
metadata:
  annotations:
    internal.kpt.dev/upstream-identifier: '|ConfigMap|${headscale-namespace}|headscale-config-init-script'
    kpt.dev/package-layer: mesh
    kpt.dev/package-name: headscale
  labels:
    app: headscale
  name: headscale-config-init-script
  namespace: headscale-system
