---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    internal.kpt.dev/upstream-identifier: apps|Deployment|porch-system|porch-controllers
    kpt.dev/package-layer: gitops
    kpt.dev/package-name: porch
  labels:
    k8s-app: porch-controllers
  name: porch-controllers
  namespace: porch-system
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: porch-controllers
  template:
    metadata:
      annotations:
        kpt.dev/package-layer: gitops
        kpt.dev/package-name: porch
      labels:
        k8s-app: porch-controllers
    spec:
      containers:
        - env:
            - name: ENABLE_PACKAGEVARIANTS
              value: "true"
            - name: ENABLE_PACKAGEVARIANTSETS
              value: "true"
          image: ghcr.io/nxmatic/porch-controllers:nxmatic-37254b4
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 5
          name: porch-controllers
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /readyz
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 3
      serviceAccountName: porch-controllers
