---
apiVersion: v1
data:
  DB_DRIVER: pgx
  DB_HOST: porch-postgresql
  DB_NAME: porch
  DB_PORT: "5432"
kind: ConfigMap
metadata:
  annotations:
    internal.kpt.dev/upstream-identifier: '|ConfigMap|porch-system|porch-db-config'
    kpt.dev/package-layer: gitops
    kpt.dev/package-name: porch
  labels:
    app.kubernetes.io/instance: porch
    app.kubernetes.io/name: postgresql
  name: porch-db-config
  namespace: porch-system
