apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    internal.kpt.dev/upstream-identifier: apps|Deployment|porch-system|function-runner
    kpt.dev/package-layer: system
    kpt.dev/package-name: porch
  name: function-runner
  namespace: porch-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: function-runner
  template:
    metadata:
      annotations:
        kpt.dev/package-layer: system
        kpt.dev/package-name: porch
      labels:
        app: function-runner
    spec:
      containers:
        - command:
            - /server
            - --config=/config.yaml
            - --functions=/functions
            - --pod-namespace=porch-fn-system
            - --max-request-body-size=6291456
            - --warm-up-pod-cache=true
          env:
            - name: WRAPPER_SERVER_IMAGE
              value: ghcr.io/nxmatic/porch-wrapper-server:nxmatic-37254b4
          image: ghcr.io/nxmatic/porch-function-runner:nxmatic-37254b4
          imagePullPolicy: IfNotPresent
          name: function-runner
          ports:
            - containerPort: 9445
          readinessProbe:
            exec:
              command:
                - /grpc-health-probe
                - -addr
                - localhost:9445
          resources:
            requests:
              cpu: 125m
              memory: 64Mi
          volumeMounts:
            - mountPath: /pod-cache-config
              name: pod-cache-config-volume
      serviceAccountName: porch-fn-runner
      volumes:
        - configMap:
            name: pod-cache-config
          name: pod-cache-config-volume
