apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: /rke2-advertise-address
  name: rke2-advertise-address
  annotations:
    config.kubernetes.io/local-config: "true"
    description.kpt.dev: Advertise address fragment
    internal.kpt.dev/upstream-identifier: '|ConfigMap|default|rke2-advertise-address'
data:
  advertise-address.yaml: |
    advertise-address: ${node-host-ip}
