apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: /rke2-cluster-init
  name: rke2-cluster-init
  annotations:
    config.kubernetes.io/local-config: "true"
    description.kpt.dev: Cluster init flag (only true on first master)
    internal.kpt.dev/upstream-identifier: '|ConfigMap|default|rke2-cluster-init'
data:
  cluster-init.yaml: |
    cluster-init: ${cluster-init}
