apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: /rke2-core
  name: rke2-core
  annotations:
    config.kubernetes.io/local-config: "true"
    description.kpt.dev: Core RKE2 settings
    internal.kpt.dev/upstream-identifier: '|ConfigMap|default|rke2-core'
data:
  core.yaml: |
    write-kubeconfig-mode: "0640"
    bind-address: "0.0.0.0"
    cni:
      - cilium
    ingress-controller: traefik
