apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: /rke2-etcd-metrics
  name: rke2-etcd-metrics
  annotations:
    config.kubernetes.io/local-config: "true"
    description.kpt.dev: Etcd metrics fragment
    internal.kpt.dev/upstream-identifier: '|ConfigMap|default|rke2-etcd-metrics'
data:
  etcd-metrics.yaml: |
    etcd-expose-metrics: true
