apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: /rke2-etcd
  name: rke2-etcd
  annotations:
    config.kubernetes.io/local-config: "true"
    description.kpt.dev: Etcd settings fragment
    internal.kpt.dev/upstream-identifier: '|ConfigMap|default|rke2-etcd'
data:
  etcd.yaml: |
    etcd-expose-metrics: true
    node-name: ${cluster-name}-${node-type}-node
    with-node-id: false
