apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: /rke2-node-ip
  name: rke2-node-ip
  annotations:
    config.kubernetes.io/local-config: "true"
    description.kpt.dev: Node IP fragment
    internal.kpt.dev/upstream-identifier: '|ConfigMap|default|rke2-node-ip'
data:
  node-ip.yaml: |
    node-ip: ${node-host-ip}
