apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: /rke2-tls-san
  name: rke2-tls-san
  annotations:
    config.kubernetes.io/local-config: "true"
    description.kpt.dev: TLS SAN fragment
    internal.kpt.dev/upstream-identifier: '|ConfigMap|default|rke2-tls-san'
data:
  tls-san.yaml: |
    tls-san:
      - localhost
      - gateway
      - 0.0.0.0
      - 127.0.0.1
      - ${cluster-vip-gateway-ip}
      - ${node-gateway-ip}
