apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: /rke2-token
  name: rke2-token
  annotations:
    config.kubernetes.io/local-config: "true"
    description.kpt.dev: RKE2 token fragment
    internal.kpt.dev/upstream-identifier: '|ConfigMap|default|rke2-token'
data:
  token.yaml: |
    token: ${cluster-token}
