apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: # kpt-merge: ${headplane-namespace}/headplane
  name: headplane
  namespace: ${headplane-namespace} # kpt-set: ${headplane-namespace}
  annotations:
    kubernetes.io/ingress.class: ${headplane-ingress-class} # kpt-set: ${headplane-ingress-class}
    internal.kpt.dev/upstream-identifier: 'networking.k8s.io|Ingress|${headplane-namespace}|headplane'
spec:
  ingressClassName: ${headplane-ingress-class} # kpt-set: ${headplane-ingress-class}
  rules:
    - host: ${headplane-ingress-host} # kpt-set: ${headplane-ingress-host}
      http:
        paths:
          - path: /admin
            pathType: Prefix
            backend:
              service:
                name: headplane
                port:
                  number: 3000
