apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata: # kpt-merge: /kdns
  name: kdns
  annotations:
    config.kubernetes.io/local-config: "true"
    internal.kpt.dev/upstream-identifier: 'kustomize.config.k8s.io|Kustomization|default|kdns'
resources:
  - overlay
