apiVersion: apps/v1
kind: Deployment
metadata: # kpt-merge: ${headscale-namespace}/headscale
  name: headscale
  namespace: ${headscale-namespace} # kpt-set: ${headscale-namespace}
  labels:
    app: headscale
  annotations:
    internal.kpt.dev/upstream-identifier: 'apps|Deployment|${headscale-namespace}|headscale'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: headscale
  template:
    metadata:
      labels:
        app: headscale
      annotations:
        flox.dev/environment: "${headscale-flox-env}" # kpt-set: ${headscale-flox-env}
    spec:
      automountServiceAccountToken: false
      nodeSelector:
        node-role.kubernetes.io/control-plane: "true"
      containers:
      - name: headscale
        image: flox/empty:1.0.0
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        - name: metrics
          containerPort: 9090
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: /etc/headscale/config.yaml
          subPath: config.yaml
        - name: acl
          mountPath: /etc/headscale/acl.json
          subPath: acl.json
        - name: derp
          mountPath: /etc/headscale/derp.yaml
          subPath: derp.yaml
        - name: data
          mountPath: /var/lib/headscale
        - name: run
          mountPath: /var/run/headscale
        command:
        - headscale
        - serve
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
            ephemeral-storage: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
            ephemeral-storage: 512Mi
        env:
        - name: FLOX_NO_TELEMETRY
          value: "1"
        - name: FLOX_NONINTERACTIVE
          value: "1"
      volumes:
      - name: config
        emptyDir: {}
      - name: acl
        configMap:
          name: headscale-acl
      - name: derp
        configMap:
          name: headscale-derp
      - name: data
        emptyDir: {}
      - name: run
        emptyDir: {}
      - configMap:
          name: headscale-config
        name: config-source
      - configMap:
          name: headscale-extra-records
        name: extra-records-source
      - configMap:
          defaultMode: 0755
          name: headscale-config-init-script
        name: config-init-script
      initContainers:
      - command:
        - bash
        - /scripts/config-init.sh
        image: flox/empty:1.0.0
        name: config-init
        volumeMounts:
        - mountPath: /config-source
          name: config-source
          readOnly: true
        - mountPath: /config
          name: config
        - mountPath: /extra-records-source
          name: extra-records-source
          readOnly: true
        - mountPath: /var/lib/headscale
          name: data
        - mountPath: /scripts
          name: config-init-script
      runtimeClassName: flox
---
apiVersion: v1
kind: Service
metadata: # kpt-merge: ${headscale-namespace}/headscale
  name: headscale
  namespace: ${headscale-namespace} # kpt-set: ${headscale-namespace}
  labels:
    app: headscale
    io.cilium/lb-ipam-pool: lan
  annotations:
    io.cilium/lb-ipam-ips: ${cluster-lan-headscale-inetaddr} # kpt-set: ${cluster-lan-headscale-inetaddr}
    tailscale.com/expose: "true"
    tailscale.com/hostname: ${cluster-name}-headscale # kpt-set: ${cluster-name}-headscale
    internal.kpt.dev/upstream-identifier: '|Service|${headscale-namespace}|headscale'
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
  selector:
    app: headscale
