apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata: # kpt-merge: /kdns-overlay
  name: kdns-overlay
  annotations:
    config.kubernetes.io/local-config: "true"
    internal.kpt.dev/upstream-identifier: 'kustomize.config.k8s.io|Kustomization|default|kdns-overlay'
resources:
  - ../base
patches:
  - path: patches/kdns-api-host.yaml
  - path: patches/kdns-dlv-sidecar.yaml
commonAnnotations:
  kpt.dev/package-layer: networking
  kpt.dev/package-name: kdns
