apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  annotations:
    config.kubernetes.io/local-config: "true"
resources:
  - ../base
patches:
  - path: patches/kdns-api-host.yaml
  - path: patches/kdns-dlv-sidecar.yaml
commonAnnotations:
  kpt.dev/package-layer: networking
  kpt.dev/package-name: kdns
