apiVersion: v1
kind: ConfigMap
metadata:
  name: rke2-advertise-address
  annotations:
    config.kubernetes.io/local-config: "true"
    description.kpt.dev: Advertise address fragment
data:
  advertise-address.yaml: |
    advertise-address: ${node-host-ip}
