apiVersion: v1
kind: ConfigMap
metadata:
  name: rke2-cluster-init
  annotations:
    config.kubernetes.io/local-config: "true"
    description.kpt.dev: Cluster init flag (only true on first master)
data:
  cluster-init.yaml: |
    cluster-init: ${cluster-init}
