apiVersion: v1
kind: ConfigMap
metadata:
  name: rke2-etcd
  annotations:
    config.kubernetes.io/local-config: "true"
    description.kpt.dev: Etcd settings fragment
data:
  etcd.yaml: |
    etcd-expose-metrics: true
    node-name: ${cluster-name}-${node-type}-node
    with-node-id: false
