apiVersion: v1
kind: ConfigMap
metadata:
  name: rke2-etcd-metrics
  annotations:
    config.kubernetes.io/local-config: "true"
    description.kpt.dev: Etcd metrics fragment
data:
  etcd-metrics.yaml: |
    etcd-expose-metrics: true
