apiVersion: v1
kind: ConfigMap
metadata:
  name: rke2-node-ip
  annotations:
    config.kubernetes.io/local-config: "true"
    description.kpt.dev: Node IP fragment
data:
  node-ip.yaml: |
    node-ip: ${node-host-ip}
