apiVersion: v1
kind: ConfigMap
metadata:
  name: rke2-node-labels
  annotations:
    config.kubernetes.io/local-config: "true"
    description.kpt.dev: Node labels fragment
data:
  node-labels.yaml: |
    node-label:
      - ${cluster-name}.cluster/node-role=${node-role}
      - ${cluster-name}.cluster/node-type=${node-type}
