apiVersion: v1
kind: ConfigMap
metadata:
  name: rke2-tls-san
  annotations:
    config.kubernetes.io/local-config: "true"
    description.kpt.dev: TLS SAN fragment
data:
  tls-san.yaml: |
    tls-san:
      - localhost
      - gateway
      - 0.0.0.0
      - 127.0.0.1
      - ${cluster-vip-gateway-ip}
      - ${node-gateway-ip}
