apiVersion: v1
kind: ConfigMap
metadata:
  name: rke2-token
  annotations:
    config.kubernetes.io/local-config: "true"
    description.kpt.dev: RKE2 token fragment
data:
  token.yaml: |
    token: ${cluster-token}
