---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    kpt.dev/package-layer: cicd
    kpt.dev/package-name: tekton-pipelines
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-pipelines
  name: config-registry-cert
  namespace: tekton-pipelines
