---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  annotations:
    internal.kpt.dev/upstream-identifier: helm.cattle.io|HelmChartConfig|kube-system|rke2-cilium
    kpt.dev/package-layer: networking
    kpt.dev/package-name: cilium-config
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: "installCRDs: true\nbpf:\n  hostLegacyRouting: true\nbgpControlPlane:\n  enabled: true\ncluster:\n  cluster-name: \n  id: \nclustermesh:\n  useAPIServer: true\n  apiserver:\n    service:\n      type: LoadBalancer\n      # Using BGP announcements for cluster mesh\nenvoy:\n  enabled: true\ngatewayAPI:\n  enabled: true\ningressController:\n  default: true\n  enabled: true\n  loadBalancerMode: dedicated\nhubble:\n  enabled: true\n  relay:\n    enabled: true\n  ui:\n    enabled: true\nipv4:\n  enabled: true\nipv6:\n  enabled: false\nkubeProxyReplacement: true\nl2announcements:\n  enabled: true\n  leaseDuration: 15s\n  leaseRenewDeadline: 5s\n  leaseRetryPeriod: 2s\nl2NeighDiscovery:\n  enabled: true\n  refresh: true\n  refreshPeriod: 30s\nl7Proxy: true\nroutingMode: tunnel\ntunnelProtocol: vxlan\noperator:\n  hostNetwork: true\n  replicas: 1\nsocketLB:\n  hostNamespaceOnly: false"
