apiVersion: v1
kind: ConfigMap
metadata:
  name: setters
  annotations:
    config.kubernetes.io/local-config: "true"
    internal.kpt.dev/function-config: apply-setters
    description.kpt.dev: Sample Porch resources setters (override per cluster downstream)
    internal.kpt.dev/upstream-identifier: '|ConfigMap|default|porch-resources-setters'
data:
  zfs-poolname: tank # kpt-set: ${zfs-poolname}
  zfs-bin: /usr/sbin/zfs # kpt-set: ${zfs-bin}
  kubelet-dir: /var/lib/kubelet # kpt-set: ${kubelet-dir}
