---
apiVersion: operator.tekton.dev/v1alpha1
kind: TektonConfig
metadata:
  annotations:
    internal.kpt.dev/upstream-identifier: operator.tekton.dev|TektonConfig|default|config
    kpt.dev/package-layer: cicd
    kpt.dev/package-name: tekton-pipelines
  name: config
spec:
  platforms: {}
  profile: all
  pruner:
    keep: 100
    resources:
      - taskrun
      - pipelinerun
    schedule: 0 8 * * *
  result:
    disabled: true
  targetNamespace: tekton-pipelines
