---
apiVersion: v1
data:
  AUTOINSTALL_COMPONENTS: "true"
  DEFAULT_TARGET_NAMESPACE: tekton-pipelines
kind: ConfigMap
metadata:
  annotations:
    internal.kpt.dev/upstream-identifier: '|ConfigMap|tekton-operator|tekton-config-defaults'
    kpt.dev/package-layer: cicd
    kpt.dev/package-name: tekton-pipelines
  labels:
    operator.tekton.dev/release: v0.78.1
  name: tekton-config-defaults
  namespace: tekton-operator
