---
apiVersion: v1
data:
  version: v0.78.1
kind: ConfigMap
metadata:
  annotations:
    internal.kpt.dev/upstream-identifier: '|ConfigMap|tekton-operator|tekton-operator-info'
    kpt.dev/package-layer: cicd
    kpt.dev/package-name: tekton-pipelines
  labels:
    app.kubernetes.io/instance: default
  name: tekton-operator-info
  namespace: tekton-operator
