---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    internal.kpt.dev/upstream-identifier: apps|Deployment|tekton-operator|tekton-operator
    kpt.dev/package-layer: cicd
    kpt.dev/package-name: tekton-pipelines
  labels:
    operator.tekton.dev/release: v0.78.1
    version: v0.78.1
  name: tekton-operator
  namespace: tekton-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: tekton-operator
  template:
    metadata:
      annotations:
        kpt.dev/package-layer: cicd
        kpt.dev/package-name: tekton-pipelines
      labels:
        app: tekton-operator
        name: tekton-operator
    spec:
      containers:
        - args:
            - -controllers
            - tektonconfig,tektonpipeline,tektontrigger,tektonhub,tektonchain,tektonresult,tektondashboard,manualapprovalgate,tektonpruner
            - -unique-process-name
            - tekton-operator-lifecycle
          env:
            - name: KUBERNETES_MIN_VERSION
              value: v1.0.0
            - name: SYSTEM_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: tekton-operator
            - name: IMAGE_PIPELINES_PROXY
              value: ghcr.io/tektoncd/operator/proxy-webhook-f6167da7bc41b96a27c5529f850e63d1:v0.78.1@sha256:cdbd01b0305088ef9e741b28347fa87de6663e043815ef8c94f6911a44d2a6fe
            - name: IMAGE_JOB_PRUNER_TKN
              value: ghcr.io/tektoncd/plumbing/tkn@sha256:233de6c8b8583a34c2379fa98d42dba739146c9336e8d41b66030484357481ed
            - name: METRICS_DOMAIN
              value: tekton.dev/operator
            - name: VERSION
              value: v0.78.1
            - name: CONFIG_OBSERVABILITY_NAME
              value: tekton-config-observability
            - name: CONFIG_LEADERELECTION_NAME
              value: tekton-operator-controller-config-leader-election
            - name: AUTOINSTALL_COMPONENTS
              valueFrom:
                configMapKeyRef:
                  key: AUTOINSTALL_COMPONENTS
                  name: tekton-config-defaults
            - name: DEFAULT_TARGET_NAMESPACE
              valueFrom:
                configMapKeyRef:
                  key: DEFAULT_TARGET_NAMESPACE
                  name: tekton-config-defaults
          image: ghcr.io/tektoncd/operator/operator-303303c315a48490ba6517859ef65b77:v0.78.1@sha256:04d34b885c168560b4562ff60918ec7aa53c6443ffa694a0c95a7c27677c0e16
          imagePullPolicy: IfNotPresent
          name: tekton-operator-lifecycle
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            seccompProfile:
              type: RuntimeDefault
        - args:
            - -controllers
            - tektoninstallerset
            - -unique-process-name
            - tekton-operator-cluster-operations
          env:
            - name: KUBERNETES_MIN_VERSION
              value: v1.0.0
            - name: SYSTEM_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: tekton-operator
            - name: PROFILING_PORT
              value: "9009"
            - name: VERSION
              value: v0.78.1
            - name: METRICS_DOMAIN
              value: tekton.dev/operator
            - name: CONFIG_LEADERELECTION_NAME
              value: tekton-operator-controller-config-leader-election
          image: ghcr.io/tektoncd/operator/operator-303303c315a48490ba6517859ef65b77:v0.78.1@sha256:04d34b885c168560b4562ff60918ec7aa53c6443ffa694a0c95a7c27677c0e16
          imagePullPolicy: IfNotPresent
          name: tekton-operator-cluster-operations
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            seccompProfile:
              type: RuntimeDefault
      serviceAccountName: tekton-operator
