---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    internal.kpt.dev/upstream-identifier: '|Secret|tekton-pipelines|tekton-docker-config'
    kpt.dev/package-layer: cicd
    kpt.dev/package-name: tekton-pipelines
    replicator.v1.mittwald.de/replicate-from: kube-system/tekton-docker-config
  name: tekton-docker-config
  namespace: tekton-pipelines
type: kubernetes.io/dockerconfigjson
