apiVersion: v1
kind: ConfigMap
metadata:
  name: set-namespace-config
  annotations:
    config.kubernetes.io/local-config: "true"
    internal.kpt.dev/function-config: set-namespace
    internal.kpt.dev/upstream-identifier: '|ConfigMap|default|set-namespace-config'
data:
  namespace: ${target-namespace} # kpt-set: ${target-namespace}
