apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- 01-configmap-flox-env.yaml
- 00-namespace.yaml
- 05-serviceaccount.yaml
- 09-configmap-flox-runtime-installer-script.yaml
- 10-daemonset.yaml
- 20-runtimeclass.yaml
commonAnnotations:
  kpt.dev/package-layer: runtime
  kpt.dev/package-name: flox-containerd-shim
