porch:
  upstream:
    repo: https://github.com/nephio-project/catalog.git
    package: /nephio/core/porch
    ref: origin/main
  images:
    server: ghcr.io/nxmatic/porch-server:nxmatic-37254b4
    controllers: ghcr.io/nxmatic/porch-controllers:nxmatic-37254b4
    functionRunner: ghcr.io/nxmatic/porch-function-runner:nxmatic-37254b4
    wrapperServer: ghcr.io/nxmatic/porch-wrapper-server:nxmatic-37254b4
  imagePullSecret: ghcr-pull
  inventory:
    name: porch-platform
    namespace: porch-system
