apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - tailscale
  - headscale
  - headplane
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata: # kpt-merge: /mesh
  name: mesh
  annotations:
    config.kubernetes.io/local-config: "true"
    internal.kpt.dev/upstream-identifier: 'kustomize.config.k8s.io|Kustomization|default|mesh'
resources:
  - tailscale
  - headscale
  - headplane
commonAnnotations: {}
