apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: /set-namespace-config
  name: set-namespace-config
  annotations:
    config.kubernetes.io/local-config: "true"
    internal.kpt.dev/function-config: set-namespace
    internal.kpt.dev/upstream-identifier: '|ConfigMap|default|set-namespace-config'
data:
  namespace: tekton-pipelines # kpt-set: ${target-namespace}
