# incus instance config (@codebase)
name: ${NODE_NAME}
architecture: aarch64
profiles:
  - ${NETWORK_NODE_PROFILE_NAME}
config:
  raw.lxc: |
    lxc.cap.drop =
    lxc.apparmor.profile = unconfined
    lxc.mount.auto = proc:rw sys:rw cgroup-full:rw
    lxc.cgroup.devices.allow = c *:* rwm
    lxc.cgroup.devices.allow = b *:* rwm
  security.privileged: true
  security.nesting: true
  volatile.lan0.hwaddr: ${NETWORK_LAN_HOST_MACADDR}
  volatile.vmnet0.hwaddr: ${NETWORK_WAN_HOST_MACADDR}
devices:
  kmsg.dev:
    type: unix-char
    source: /dev/kmsg
    path: /dev/kmsg
  zfs.dev:
    type: unix-char
    source: /dev/zfs
    path: /dev/zfs
  secrets.file:
    type: disk
    source: ${INCUS_SECRETS_FILE}
    path: /srv/host/secrets
  rke2lab.env.file:
    type: disk
    source: ${INCUS_ENV_FILE}
    path: /srv/host/environment
  rke2lab.scripts.dir:
    type: disk
    source: ${INCUS_SCRIPTS_DIR}
    path: /srv/host/scripts.d
  rke2lab.system.dir:
    type: disk
    source: ${INCUS_SYSTEMD_DIR}
    path: /srv/host/system.d
  manifests.dir:
    type: disk
    source: ${KPT_MANIFESTS_DIR}
    path: /srv/host/manifests.d
  rke2.config.dir:
    type: disk
    source: ${KPT_CONFIG_DIR}
    path: /srv/host/config.d
  shared.dir:
    type: disk
    source: ${INCUS_SHARED_DIR}
    path: /srv/host/share.d
  kubeconfig.dir:
    type: disk
    source: ${INCUS_KUBECONFIG_DIR}
    path: /srv/host/kubeconfig.d
  user.metadata:
    type: disk
    source: ${CLOUDCONFIG_METADATA_FILE}
    path: /var/lib/cloud/seed/nocloud/meta-data
  user.user-data:
    type: disk
    source: ${CLOUDCONFIG_USERDATA_FILE}
    path: /var/lib/cloud/seed/nocloud/user-data
  user.network-config:
    type: disk
    source: ${CLOUDCONFIG_NETCFG_FILE}
    path: /var/lib/cloud/seed/nocloud/network-config
