# incus instance config (@codebase)
name: ${NODE_NAME}
architecture: aarch64
profiles:
  - ${NODE_PROFILE_NAME}
config:
  raw.lxc: |
    lxc.cap.drop =
    lxc.apparmor.profile = unconfined
    lxc.mount.auto = proc:rw sys:rw cgroup-full:rw
    lxc.cgroup.devices.allow = c *:* rwm
    lxc.cgroup.devices.allow = b *:* rwm
  security.privileged: true
  security.nesting: true
  # RKE2 Core Configuration
  environment.DEBUG: true
  environment.NODE_TYPE: "${NODE_TYPE}"
  environment.CLUSTER_NAME: "${CLUSTER_NAME}"
  environment.CLUSTER_TOKEN: "${CLUSTER_TOKEN}"
  environment.CLUSTER_DOMAIN: "${CLUSTER_DOMAIN}"
  environment.NODE_ROLE: "${NODE_ROLE}"
  environment.NODE_NAME: "${NODE_NAME}"
  environment.POD_NETWORK_CIDR: "${POD_NETWORK_CIDR}"
  environment.SERVICE_NETWORK_CIDR: "${SERVICE_NETWORK_CIDR}"
  # RKE2 Network Configuration
  environment.CLUSTER_ID: "${CLUSTER_ID}"
  environment.NODE_ID: "${NODE_ID}"
  environment.NODE_HOST_IP: "${NODE_HOST_IP}"
  environment.NODE_VIP_IP: "${NODE_VIP_IP}"
  environment.NODE_NETWORK_CIDR: "${NODE_NETWORK_CIDR}"
  environment.NODE_GATEWAY_IP: "${NODE_GATEWAY_IP}"
  environment.CLUSTER_VIP_INTERFACE_NAME: "${CLUSTER_VIP_INTERFACE_NAME}"
  environment.CLUSTER_VIP_NETWORK_CIDR: "${CLUSTER_VIP_NETWORK_CIDR}"
  environment.NODE_LAN_INTERFACE_NAME: "${NODE_LAN_INTERFACE_NAME}"
  environment.NODE_WAN_INTERFACE_NAME: "${NODE_WAN_INTERFACE_NAME}"
  # Tailscale Configuration
  environment.TSID: "${TSID}"
  environment.TSKEY_CLIENT: "${TSKEY_CLIENT}" # canonical secret variable (@codebase)
devices:
  kmsg.dev:
    type: unix-char
    source: /dev/kmsg
    path: /dev/kmsg
  zfs.dev:
    type: unix-char
    source: /dev/zfs
    path: /dev/zfs
  secrets.dir:
    type: disk
    source: ${PWD}/.secrets.d
    path: /.secrets.d
    readonly: "true"
  shared.dir:
    type: disk
    source: ${PWD}/${RUN_INSTANCE_DIR}/shared
    path: /.shared.d
  logs.dir:
    type: disk
    source: ${PWD}/${RUN_INSTANCE_DIR}/logs
    path: /.logs.d
  kubeconfig.dir:
    type: disk
    source: ${PWD}/${RUN_INSTANCE_DIR}/kube
    path: /.kubeconfig.d
  user.metadata:
    type: disk
    source: ${PWD}/${RUN_NOCLOUD_METADATA_FILE}
    path: /var/lib/cloud/seed/nocloud/meta-data
  user.user-data:
    type: disk
    source: ${PWD}/${RUN_NOCLOUD_USERDATA_FILE}
    path: /var/lib/cloud/seed/nocloud/user-data
  user.network-config:
    type: disk
    source: ${PWD}/${RUN_NOCLOUD_NETCFG_FILE}
    path: /var/lib/cloud/seed/nocloud/network-config
