apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: kdns-base
  annotations:
    config.kubernetes.io/local-config: "true"
resources:
- 02-configmap-kdns-dlv-script.yaml
- clusterrole_kdns-ingress-reader.yaml
- ${target-namespace}/clusterrolebinding_kdns-ingress-reader-binding.yaml # kpt-set: ${target-namespace}/clusterrolebinding_kdns-ingress-reader-binding.yaml
- ${target-namespace}/deployment_kdns.yaml # kpt-set: ${target-namespace}/deployment_kdns.yaml
- ${target-namespace}/serviceaccount_kdns.yaml # kpt-set: ${target-namespace}/serviceaccount_kdns.yaml

