---
apiVersion: cilium.io/v2
kind: CiliumBGPClusterConfig
metadata:
  annotations:
    internal.kpt.dev/upstream-identifier: cilium.io|CiliumBGPClusterConfig|default|bgp-cluster-config
    kpt.dev/package-layer: networking
    kpt.dev/package-name: cilium-advanced
  name: bgp-cluster-config
spec:
  bgpInstances:
    - localASN: 65010
      name: control-plane-bgp
      peers:
        - name: gateway-peer
          peerASN: 65020
          peerAddress: 10.80.8.1
          peerConfigRef:
            name: cilium-peer
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/control-plane: ""
