apiVersion: v1
kind: ConfigMap
metadata:
  name: cilium-setters
  annotations:
    config.kubernetes.io/local-config: "true"
    internal.kpt.dev/function-config: apply-setters
    description.kpt.dev: Local setters for HelmChartConfig substitution within cilium-config
data:
  cluster-name: sample
  cluster-id: 7
