---
apiVersion: v1
data:
  HEADPLANE_NAMESPACE: headscale-system
  HEADSCALE_NAMESPACE: headscale-system
kind: ConfigMap
metadata:
  annotations:
    internal.kpt.dev/upstream-identifier: '|ConfigMap|${headscale-namespace}|headplane-env'
    kpt.dev/package-layer: mesh
    kpt.dev/package-name: headplane
  name: headplane-env
  namespace: headscale-system
