---
apiVersion: v1
data:
  HEADPLANE_BASE_URL: http://headplane.headplane.svc.cluster.local:3000
  HEADPLANE_COOKIE_SECURE: "true"
  HEADPLANE_NAMESPACE: headscale-system
  HEADSCALE_NAMESPACE: headscale-system
  HEADSCALE_SERVICE_URL: http://headscale.headscale-system.svc.cluster.local:8080
kind: ConfigMap
metadata:
  annotations:
    internal.kpt.dev/upstream-identifier: '|ConfigMap|${headscale-namespace}|headplane-env'
    kpt.dev/package-layer: mesh
    kpt.dev/package-name: headplane
  name: headplane-env
  namespace: headscale-system
