---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    internal.kpt.dev/upstream-identifier: networking.k8s.io|Ingress|${headscale-namespace}|headplane
    kpt.dev/package-layer: mesh
    kpt.dev/package-name: headplane
    kubernetes.io/ingress.class: cilium
  name: headplane
  namespace: headscale-system
spec:
  ingressClassName: cilium
  rules:
    - host: headplane.local
      http:
        paths:
          - backend:
              service:
                name: headplane
                port:
                  number: 3000
            path: /admin
            pathType: Prefix
