---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    internal.kpt.dev/upstream-identifier: '|Secret|${headscale-namespace}|headplane-config-tmpl'
    kpt.dev/package-layer: mesh
    kpt.dev/package-name: headplane
  name: headplane-config-tmpl
  namespace: headscale-system
stringData:
  config.yaml: |-
    server:
      host: "0.0.0.0"
      port: 3000
      base_url: "${HEADPLANE_BASE_URL}"
      cookie_secret_path: "/etc/headplane/secrets/cookie_secret"
      cookie_secure: ${HEADPLANE_COOKIE_SECURE}
      data_path: "/var/lib/headplane"

    headscale:
      url: "${HEADSCALE_SERVICE_URL}"
      config_path: "/etc/headscale/config.yaml"
      dns_records_path: "/var/lib/headscale/extra_records.json"
      config_strict: true

    integration:
      agent:
        enabled: true
        pre_authkey_path: "/etc/headplane/agent/preauthkey"
      kubernetes:
        enabled: true
        validate_manifest: true
        pod_name: "headscale"
type: Opaque
