apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: /rke2-cluster-init
  name: cluster-init.yaml
  annotations:
    description.kpt.dev: Cluster init flag (only true on first master)
    config.kubernetes.io/local-config: "true"
    internal.kpt.dev/upstream-identifier: '|ConfigMap|default|rke2-cluster-init'
data:
  cluster-init: ${cluster-init} # kpt-set: ${cluster-init}
