apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: /rke2-etcd-metrics
  name: etcd-metrics.yaml
  annotations:
    description.kpt.dev: Etcd metrics fragment
    config.kubernetes.io/local-config: "true"
    internal.kpt.dev/upstream-identifier: '|ConfigMap|default|rke2-etcd-metrics'
data:
  etcd-expose-metrics: true
