apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: /rke2-network-cidrs
  name: network-cidrs.yaml
  annotations:
    description.kpt.dev: Network CIDRs fragment
    config.kubernetes.io/local-config: "true"
    internal.kpt.dev/upstream-identifier: '|ConfigMap|default|rke2-network-cidrs'
data:
  cluster-cidr: ${pod-network-cidr} # kpt-set: ${pod-network-cidr}
  service-cidr: ${service-network-cidr} # kpt-set: ${service-network-cidr}
  kube-controller-manager-arg:
    - node-cidr-mask-size-ipv4=24
