apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: /rke2-node-inetaddr
  name: node-inetaddr.yaml
  annotations:
    description.kpt.dev: Node IP fragment
    config.kubernetes.io/local-config: "true"
    internal.kpt.dev/upstream-identifier: '|ConfigMap|default|rke2-node-inetaddr'
data:
  node-inetaddr: ${node-host-inetaddr} # kpt-set: ${node-host-inetaddr}
