apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: /rke2-node-labels
  name: node-labels.yaml
  annotations:
    description.kpt.dev: Node labels fragment
    config.kubernetes.io/local-config: "true"
    internal.kpt.dev/upstream-identifier: '|ConfigMap|default|rke2-node-labels'
data:
  node-label:
    - ${cluster-name}.cluster/node-role=${node-role} # kpt-set: ${cluster-name}.cluster/node-role=${node-role}
    - ${cluster-name}.cluster/node-type=${node-type} # kpt-set: ${cluster-name}.cluster/node-type=${node-type}
