apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- release-operator-v0.78.1.yaml
- tektonconfig-all.yaml
commonAnnotations:
  kpt.dev/package-layer: cicd
  kpt.dev/package-name: tekton-pipelines
