apiVersion: operator.tekton.dev/v1alpha1
kind: TektonConfig
metadata: # kpt-merge: /config
  name: config
  annotations:
    internal.kpt.dev/upstream-identifier: 'operator.tekton.dev|TektonConfig|default|config'
spec:
  profile: all
  targetNamespace: tekton-pipelines
  result:
    disabled: true
  pruner:
    resources:
      - taskrun
      - pipelinerun
    keep: 100
    schedule: "0 8 * * *"
