---
apiVersion: v1
data:
  FLOX_DISABLE_METRICS: "true"
  FLOX_NO_TELEMETRY: "1"
  FLOX_NONINTERACTIVE: "1"
kind: ConfigMap
metadata:
  annotations:
    internal.kpt.dev/upstream-identifier: '|ConfigMap|${headscale-namespace}|flox-env'
    kpt.dev/package-layer: runtime
    kpt.dev/package-name: flox-containerd-shim
  name: flox-env
  namespace: flox-runtime
