apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: porch-system/porch-config
  namespace: porch-system
  name: porch-config
  annotations:
    config.kubernetes.io/local-config: "true"
    internal.kpt.dev/upstream-identifier: '|ConfigMap|porch-system|porch-config'
data:
  cache-type: DB
