apiVersion: v1
kind: ConfigMap
metadata:
  name: headplane-env
  namespace: ${headscale-namespace} # kpt-set: ${headscale-namespace}
data:
  HEADPLANE_NAMESPACE: ${headscale-namespace} # kpt-set: ${headscale-namespace}
  HEADSCALE_NAMESPACE: ${headscale-namespace} # kpt-set: ${headscale-namespace}
