apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: headplane
  annotations:
    config.kubernetes.io/local-config: "true"  
resources:
- 01-secret-headplane-agent-auth.yaml
- 01-secret-headplane-config-tmpl.yaml
- 01-secret-headplane-secrets.yaml
- 02-pvc-headplane-data.yaml
- 03-rbac-headplane.yaml
- 03-serviceaccount-headplane.yaml
- 02-configmap-headplane-env.yaml
- 04-configmap-headplane-agent-sync-script.yaml
- 04-job-headplane-agent-sync.yaml
- 05-deployment-headplane.yaml
- 06-service-headplane.yaml
- 07-ingress-headplane.yaml
commonAnnotations:
  kpt.dev/package-layer: mesh
  kpt.dev/package-name: headplane
