---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    internal.kpt.dev/upstream-identifier: apps|Deployment|porch-system|porch-server
    kpt.dev/package-layer: gitops
    kpt.dev/package-name: porch
  name: porch-server
  namespace: porch-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: porch-server
  template:
    metadata:
      annotations:
        kpt.dev/package-layer: gitops
        kpt.dev/package-name: porch
      labels:
        app: porch-server
    spec:
      automountServiceAccountToken: false
      containers:
        - args:
            - --function-runner=function-runner:9445
            - --cache-directory=/cache
            - --cert-dir=/tmp/certs
            - --secure-port=4443
            - --repo-sync-frequency=3m
            - --repo-operation-retry-attempts=3
            - --max-request-body-size=6291456
          env:
            - name: OTEL_SERVICE_NAME
              value: porch-server
            - name: CERT_STORAGE_DIR
              value: /etc/webhook/certs
            - name: GOOGLE_API_GO_EXPERIMENTAL_DISABLE_NEW_AUTH_LIB
              value: "true"
          image: ghcr.io/nxmatic/porch-server:v1.5.5
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 4443
              scheme: HTTPS
            initialDelaySeconds: 30
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 5
          name: porch-server
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /readyz
              port: 4443
              scheme: HTTPS
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 3
          resources:
            limits:
              cpu: 500m
              ephemeral-storage: 512Mi
              memory: 512Mi
            requests:
              cpu: 100m
              ephemeral-storage: 256Mi
              memory: 128Mi
          securityContext:
            runAsGroup: 65532
            runAsNonRoot: true
            runAsUser: 65532
          volumeMounts:
            - mountPath: /usr/bin/git
              name: git-bin
              subPath: git
            - mountPath: /usr/bin/git-remote-https
              name: git-bin
              subPath: git-remote-https
            - mountPath: /cache
              name: cache-volume
            - mountPath: /etc/webhook/certs
              name: webhook-certs
            - mountPath: /tmp/certs
              name: api-server-certs
      initContainers:
        - command:
            - sh
            - /scripts/install-git.sh
          image: alpine:latest
          name: install-git
          securityContext:
            runAsUser: 0
          volumeMounts:
            - mountPath: /git-bin
              name: git-bin
            - mountPath: /scripts
              name: porch-git-script
              readOnly: true
      serviceAccountName: porch-server
      volumes:
        - emptyDir: {}
          name: git-bin
        - configMap:
            defaultMode: 493
            name: porch-git-script
          name: porch-git-script
        - emptyDir: {}
          name: cache-volume
        - emptyDir: {}
          name: webhook-certs
        - emptyDir: {}
          name: api-server-certs
